In [34]:
from functools import partial
from itertools import repeat, islice, count, combinations, starmap
from operator import mul
import numpy as np
import pandas as pd

In [2]:
def take(iterable, n):
    return list(islice(iterable, n))

In [3]:
def godel_beta(seq):
    return None

In [4]:
# sample sequence of length n
seq_list = [31, 5, 51, 0, 2]
seq = np.array(seq_list)
seq

array([31,  5, 51,  0,  2])

In [5]:
n = len(seq)

In [6]:
# range of seq index (length n-1)
indices = range(1,n)
assert len(indices) == n-1
list(indices)

[1, 2, 3, 4]

In [7]:
m0 = np.lcm.reduce(indices)
m0

12

In [8]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])

In [9]:
a < b

array([ True,  True, False, False])

In [10]:
ms = map(partial(mul, m0), count(1))
ms

In [11]:
take(ms,5)

[12, 24, 36, 48, 60]

In [12]:
def mi_seq(n, m):
    return [(i+1)*m+1 for i in range(n)]

In [13]:
mis = mi_seq(n, 12)
mis

[13, 25, 37, 49, 61]

In [14]:
seq<mis

array([False,  True, False,  True,  True])

In [15]:
seq < mi_seq(n, 24)

array([False,  True,  True,  True,  True])

In [16]:
seq < mi_seq(n, 36)

array([ True,  True,  True,  True,  True])

In [17]:
#import sympy
from sympy.ntheory.modular import crt

In [21]:
list(mi_seq(n,36))

[37, 73, 109, 145, 181]

In [22]:
list(seq)

[31, 5, 51, 0, 2]

In [39]:
x, M = crt([37, 73, 109, 145, 181], [31, 5, 51, 0, 2])
x,M

(mpz(2496662055), 7726764205)

In [26]:
crt(mi_seq(n,36), seq)

ValueError: 31 is not an integer

In [43]:
combs = combinations(mi_seq(n,36) ,2)
print(list(combs))
gcds = starmap(math.gcd, combs)

[(37, 73), (37, 109), (37, 145), (37, 181), (73, 109), (73, 145), (73, 181), (109, 145), (109, 181), (145, 181)]


In [44]:
np.gcd(combs)

ValueError: invalid number of arguments

In [37]:
list(gcds)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [41]:
check = [x % m for m in mi_seq(n,36)]
print(check)

[mpz(31), mpz(5), mpz(51), mpz(0), mpz(2)]
